services:
    oh_media_antispam.form.type.recaptcha:
        class: OHMedia\AntispamBundle\Form\Type\RecaptchaType
        arguments: ["%oh_media_antispam.recaptcha.sitekey%", "%oh_media_antispam.recaptcha.theme%", "%oh_media_antispam.recaptcha.size%"]
        tags:
            - { name: form.type }

    oh_media_antispam.validator.recaptcha:
        class: OHMedia\AntispamBundle\Validator\RecaptchaValidator
        arguments: ["@request_stack", "%oh_media_antispam.recaptcha.secretkey%"]
        tags:
            - { name: validator.constraint_validator }
