services:
    OHMedia\AntispamBundle\Form\Type\RecaptchaType:
        arguments: ["%oh_media_antispam.recaptcha.sitekey%", "%oh_media_antispam.recaptcha.theme%", "%oh_media_antispam.recaptcha.size%"]
        tags:
            - { name: form.type }

    oh_media_antispam.form.type.recaptcha:
        alias: OHMedia\AntispamBundle\Form\Type\RecaptchaType

    OHMedia\AntispamBundle\Validator\RecaptchaValidator:
        arguments: ["@request_stack", "%oh_media_antispam.recaptcha.secretkey%"]
        tags:
            - { name: validator.constraint_validator }

    oh_media_antispam.validator.recaptcha:
        alias: OHMedia\AntispamBundle\Validator\RecaptchaValidator

    OHMedia\AntispamBundle\Form\Extension\FormTypeHoneypotExtension:
        tags:
            - { name: form.type_extension }

    OHMedia\AntispamBundle\Twig\Extension\RecaptchaExtension:
        tags:
            - { name: twig.extension }
